### ISSUE TITLE
How can I use the code for detection? I find the repo was used for classify

### ISSUE THREAD

**Issue by csq20081052** [nicolefinnie/TFdetect#5]
As I build the .apk and install it to my phone. find it was used for classify. How can I used it to detect with bounding box around the target as your picture showed.

**Comment by csq20081052** [comment]
I had just solved this problem.Thanks!

**Comment by nicolefinnie** [comment]
@csq20081052  ah cool, I'm glad you figured it out quickly I didn't even get a chance to look at the issue before you closed it.
